ALTER TABLE mycalories.USER CHANGE COLUMN EMAIL NAME VARCHAR(1024) NOT NULL;
ALTER TABLE mycalories.USER ADD CONSTRAINT user_unique_key UNIQUE(NAME);

ALTER TABLE mycalories.USER ADD COLUMN EMAIL VARCHAR(250);


